### ISSUE TITLE
Yaml-cpp: error at line 0, column 0: bad conversion

### ISSUE THREAD

**Issue by GianlucaBelardinelli** [patrickmoore/Mu#3] opened 2016-09-22 17:26 UTC
Hi,

I just recorded now a stint and while converting the file using your tool I get the following error:
`[Error] yaml-cpp: error at line 0, column 0: bad conversion`
Mu version: 1.7.3.2

**Comment by patrickmoore** [comment] 2016-09-22 20:57
Hi Gianluca.  Are you able to send me offending .ibt file?

**Comment by GianlucaBelardinelli** [comment] 2016-09-26 12:29
You have a dropbox file shared. Check your Gmail. I've used the one on the Mu readme description.

Thanks

**Comment by patrickmoore** [comment] 2016-09-27 16:51
The problem is due to malformed YAML coming from iRacing.  Specifically, the DriverSetupName node is not quoted.  I've sent a message to David Tucker about the issue but I'll also add in this sanitizing case to Mu.

**Comment by patrickmoore** [comment] 2016-11-04 06:06
Fixed with 1.7.3.3

**Closed by patrickmoore** 2016-11-04 06:06 UTC
